version: "3.8"

services:
  chimpanzee:
    build: .
    environment:
      - CHIMPANZEE_DB_USER=pguser
      - CHIMPANZEE_DB_PASSWORD=pgpass
      - CHIMPANZEE_DB_DATABASE=pgdb
      - CHIMPANZEE_DB_HOST=db
      - CHIMPANZEE_DB_PORT=5432
      - CHIMPANZEE_SERVICE_DEBUG=true
      - CHIMPANZEE_SERVICE_PORT=8087
    ports:
      - "8080:8087"
    depends_on:
      - db

  db:
    image: postgres:13.3-alpine
    volumes:
      - ./datadir/postgresql/data:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=pguser
      - POSTGRES_DB=pgdb
